<!DOCTYPE html>
<html lang="fr-ca">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">
    <meta name="description"
          content="Site de streaming vidéo priver, je suis responsable de aucune vidéo qui serait soumise à des droits d'auteur."/>
    <title>Punch</title>

    <!--    //bibliothèque de style et js personnel-->
    <link rel="stylesheet" href="css/card.css">
    <link rel="stylesheet" href="css/navbar.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/bootstrap.min.css">




</head>

<body onload=display_ct();>



<nav class="navbar">
    <div class="container">
        <div class="navmenu">
            <div class="menubar">
				<span class="openmenu" id="openmenu">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="16">
						<g fill="#252a32" fill-rule="evenodd">
							<path d="M0 0h24v2H0zM0 7h24v2H0zM0 14h24v2H0z" />
						</g>
					</svg>
				</span>
            </div>
            <div class="brandbar">
                <h1><a href="index.php" class="brand">Punch</a></h1>
            </div>
            <div class="userbar"></div>
        </div>
    </div>
</nav>
<section class="navmodal" id="navmodal">
    <div class="container">
		<span class="closemenu" id="closemenu">
			<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
				<path fill="#252a32" fill-rule="evenodd" d="M17.778.808l1.414 1.414L11.414 10l7.778 7.778-1.414 1.414L10 11.414l-7.778 7.778-1.414-1.414L8.586 10 .808 2.222 2.222.808 10 8.586 17.778.808z" />
			</svg>
		</span>
        <div class="navmodal-wrapper">
            <div class="column">
                <h4 class="subtitle">ADMINISTRATION</h4>
                <ul class="menu">
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Ajout</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Log</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Statistique</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Configuration</a></li>
                </ul>
            </div>
            <div class="column">
                <h4 class="subtitle">EMPLOYER</h4>
                <ul class="menu">
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Votre semaine</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Votre année</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Vos information</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Statistique</a></li>
                </ul>
            </div>
            <div class="column">
                <h4 class="subtitle">ERREUR PRÉSENTE</h4>
                <ul class="menu">
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">To do list</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Réparer</a></li>

                </ul>
            </div>
            <div class="column">
                <h4 class="subtitle">FICHE PERSONNELLE</h4>
                <ul class="menu">
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">John</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Skooma</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">Masafa56</a></li>
                    <li class="menu-item"><a href="dashboard.php" class="menu-link">G.I.JOE</a></li>
                </ul>
            </div>

        </div>

    </div>
</section>
<main>
    <div class="container">

    </div>
</main>